#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using PhotosDAL;

namespace PhotosDAL	
{
	[System.Serializable()]
	public partial class PhotoSource : System.Runtime.Serialization.ISerializable
	{
		private int _sourceID;
		public virtual int SourceID
		{
			get
			{
				return this._sourceID;
			}
			set
			{
				this._sourceID = value;
			}
		}
		
		private string _sourceName;
		public virtual string SourceName
		{
			get
			{
				return this._sourceName;
			}
			set
			{
				this._sourceName = value;
			}
		}
		
		private IList<Photo> _photos = new List<Photo>();
		public virtual IList<Photo> Photos
		{
			get
			{
				return this._photos;
			}
		}
		
		#region ISerializable Implementation
		
		public PhotoSource()
		{
		}
		
		protected PhotoSource(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.SourceID = info.GetInt32("SourceID");
			this.SourceName = info.GetString("SourceName");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("SourceID", this.SourceID, typeof(int));
			info.AddValue("SourceName", this.SourceName, typeof(string));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
