#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using PhotosDAL;

namespace PhotosDAL	
{
	public partial class PhotosModel : OpenAccessContext, IPhotosModelUnitOfWork
	{
		private static string connectionStringName = @"FullHouseEntertainmentConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("PhotosModel.rlinq");
		
		public PhotosModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public PhotosModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public PhotosModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public PhotosModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public PhotosModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<PhotoSource> PhotoSources 
		{
			get
			{
				return this.GetAll<PhotoSource>();
			}
		}
		
		public IQueryable<Photo> Photos 
		{
			get
			{
				return this.GetAll<Photo>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MySql";
			backend.ProviderName = "MySql.Data.MySqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of PhotosModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of PhotosModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IPhotosModelUnitOfWork : IUnitOfWork
	{
		IQueryable<PhotoSource> PhotoSources
		{
			get;
		}
		IQueryable<Photo> Photos
		{
			get;
		}
	}
}
#pragma warning restore 1591
