#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using PhotosDAL;

namespace PhotosDAL	
{
	[System.Serializable()]
	public partial class Photo : System.Runtime.Serialization.ISerializable
	{
		private int _photoID;
		public virtual int PhotoID
		{
			get
			{
				return this._photoID;
			}
			set
			{
				this._photoID = value;
			}
		}
		
		private string _sourcePhotoID;
		public virtual string SourcePhotoID
		{
			get
			{
				return this._sourcePhotoID;
			}
			set
			{
				this._sourcePhotoID = value;
			}
		}
		
		private int _sourceID;
		public virtual int SourceID
		{
			get
			{
				return this._sourceID;
			}
			set
			{
				this._sourceID = value;
			}
		}
		
		private DateTime _captured;
		public virtual DateTime Captured
		{
			get
			{
				return this._captured;
			}
			set
			{
				this._captured = value;
			}
		}
		
		private DateTime _photoDate;
		public virtual DateTime PhotoDate
		{
			get
			{
				return this._photoDate;
			}
			set
			{
				this._photoDate = value;
			}
		}
		
		private string _localPath;
		public virtual string LocalPath
		{
			get
			{
				return this._localPath;
			}
			set
			{
				this._localPath = value;
			}
		}
		
		private PhotoSource _photoSource;
		public virtual PhotoSource PhotoSource
		{
			get
			{
				return this._photoSource;
			}
			set
			{
				this._photoSource = value;
			}
		}
		
		#region ISerializable Implementation
		
		public Photo()
		{
		}
		
		protected Photo(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.PhotoID = info.GetInt32("PhotoID");
			this.SourcePhotoID = info.GetString("SourcePhotoID");
			this.SourceID = info.GetInt32("SourceID");
			this.Captured = (DateTime)info.GetValue("Captured", typeof(DateTime));
			this.PhotoDate = (DateTime)info.GetValue("PhotoDate", typeof(DateTime));
			this.LocalPath = info.GetString("LocalPath");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("PhotoID", this.PhotoID, typeof(int));
			info.AddValue("SourcePhotoID", this.SourcePhotoID, typeof(string));
			info.AddValue("SourceID", this.SourceID, typeof(int));
			info.AddValue("Captured", this.Captured, typeof(DateTime));
			info.AddValue("PhotoDate", this.PhotoDate, typeof(DateTime));
			info.AddValue("LocalPath", this.LocalPath, typeof(string));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
